In [2]:
import pandas as pd

In [5]:
df=pd.read_csv('trees.csv',index_col='the_geom')
print(df.shape)
#No duplicates.  
df.drop_duplicates(inplace=True)
print(df.shape)
df.head()

(683788, 41)
(683788, 41)

,created_at,tree_id,block_id,tree_dbh,stump_diam,curb_loc,status,health,spc_latin,spc_common,...,st_assem,st_senate,nta,nta_name,boro_ct,state,Latitude,longitude,x_sp,y_sp
the_geom,,,,,,,,,,,,,,,,,,,,,
POINT (-73.84421521958048 40.723091773924274),08/27/2015,180683,348711,3,0,OnCurb,Alive,Fair,Acer rubrum,red maple,...,28,16,QN17,Forest Hills,4073900,New York,40.723092,-73.844215,1.027431e+06,202756.768749
POINT (-73.81867945834878 40.79411066708779),09/03/2015,200540,315986,21,0,OnCurb,Alive,Fair,Quercus palustris,pin oak,...,27,11,QN49,Whitestone,4097300,New York,40.794111,-73.818679,1.034456e+06,228644.837379
POINT (-73.93660770459083 40.717580740099116),09/05/2015,204026,218365,3,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,50,18,BK90,East Williamsburg,3044900,New York,40.717581,-73.936608,1.001823e+06,200716.891267
POINT (-73.93445615919741 40.713537494833226),09/05/2015,204337,217969,10,0,OnCurb,Alive,Good,Gleditsia triacanthos var. inermis,honeylocust,...,53,18,BK90,East Williamsburg,3044900,New York,40.713537,-73.934456,1.002420e+06,199244.253136
POINT (-73.97597938483258 40.66677775537875),08/30/2015,189565,223043,21,0,OnCurb,Alive,Good,Tilia americana,American linden,...,44,21,BK37,Park Slope-Gowanus,3016500,New York,40.666778,-73.975979,9.909138e+05,182202.425999

In [16]:
# print(df.isnull().sum())
# print(df.isna().sum())
print(df.shape)
# The dataset contains no missing values ("" or null)  
# Can you fill in some missing values ?
df.dropna(inplace=True)
print(df.shape)

(683788, 41)
(652118, 41)

In [17]:
df.head().T

the_geom,POINT (-73.84421521958048 40.723091773924274),POINT (-73.81867945834878 40.79411066708779),POINT (-73.93660770459083 40.717580740099116),POINT (-73.93445615919741 40.713537494833226),POINT (-73.97597938483258 40.66677775537875)
created_at,08/27/2015,09/03/2015,09/05/2015,09/05/2015,08/30/2015
tree_id,180683,200540,204026,204337,189565
block_id,348711,315986,218365,217969,223043
tree_dbh,3,21,3,10,21
stump_diam,0,0,0,0,0
curb_loc,OnCurb,OnCurb,OnCurb,OnCurb,OnCurb
status,Alive,Alive,Alive,Alive,Alive
health,Fair,Fair,Good,Good,Good
spc_latin,Acer rubrum,Quercus palustris,Gleditsia triacanthos var. inermis,Gleditsia triacanthos var. inermis,Tilia americana
spc_common,red maple,pin oak,honeylocust,honeylocust,American linden
steward,None,None,1or2,None,None
guards,None,None,None,None,None
sidewalk,NoDamage,Damage,Damage,Damage,Damage
user_type,TreesCount Staff,TreesCount Staff,Volunteer,Volunteer,Volunteer
problems,None,Stones,None,Stones,Stones
root_stone,No,Yes,No,Yes,Yes
root_grate,No,No,No,No,No
root_other,No,No,No,No,No
trnk_wire,No,No,No,No,No
trnk_light,No,No,No,No,No
trnk_other,No,No,No,No,No
brnch_ligh,No,No,No,No,No
brnch_shoe,No,No,No,No,No
brnch_othe,No,No,No,No,No
address,108-005 70 AVENUE,147-074 7 AVENUE,390 MORGAN AVENUE,1027 GRAND STREET,603 6 STREET
zipcode,11375,11357,11211,11211,11215
zip_city,Forest Hills,Whitestone,Brooklyn,Brooklyn,Brooklyn
cb_num,406,407,301,301,306
borocode,4,4,3,3,3
boroname,Queens,Queens,Brooklyn,Brooklyn,Brooklyn
cncldist,29,19,34,34,39
st_assem,28,27,50,53,44
st_senate,16,11,18,18,21
nta,QN17,QN49,BK90,BK90,BK37
nta_name,Forest Hills,Whitestone,East Williamsburg,East Williamsburg,Park Slope-Gowanus
boro_ct,4073900,4097300,3044900,3044900,3016500
state,New York,New York,New York,New York,New York
Latitude,40.7231,40.7941,40.7176,40.7135,40.6668
longitude,-73.8442,-73.8187,-73.9366,-73.9345,-73.976
x_sp,1.02743e+06,1.03446e+06,1.00182e+06,1.00242e+06,990914
y_sp,202757,228645,200717,199244,182202

In [19]:
for idx,name in enumerate(df):
    print(df[name].value_counts())

10/27/2015    6494
10/13/2015    6328
10/29/2015    5942
10/26/2015    5925
11/03/2015    5712
              ...
02/13/2016       9
03/02/2016       6
10/04/2016       6
04/03/2016       4
03/14/2016       2
Name: created_at, Length: 483, dtype: int64
2047      1
366616    1
368671    1
370718    1
372765    1
         ..
466358    1
460213    1
462260    1
472499    1
2049      1
Name: tree_id, Length: 652118, dtype: int64
204850    440
602362    356
208115    241
506756    206
233208    194
         ...
300658      1
314812      1
312101      1
102881      1
107219      1
Name: block_id, Length: 100693, dtype: int64
4      58146
3      51620
5      40701
2      38480
11     37584
       ...
75         1
151        1
154        1
159        1
425        1
Name: tree_dbh, Length: 145, dtype: int64
0    652118
Name: stump_diam, dtype: int64
OnCurb            626254
OffsetFromCurb     25864
Name: curb_loc, dtype: int64
Alive    652118
Name: status, dtype: int64
Good    528805
Fair     96497
Poor     26816
Name: health, dtype: int64
Platanus x acerifolia                 87012
Gleditsia triacanthos var. inermis    64258
Pyrus calleryana                      58924
Quercus palustris                     53179
Acer platanoides                      34189
                                      ...
Pinus nigra                              37
Pinus rigida                             33
Maclura pomifera                         29
Pinus sylvestris                         25
Pinus virginiana                         10
Name: spc_latin, Length: 132, dtype: int64
London planetree    87012
honeylocust         64258
Callery pear        58924
pin oak             53179
Norway maple        34189
                    ...
black pine             37
pitch pine             33
Osage-orange           29
Scots pine             25
Virginia pine          10
Name: spc_common, Length: 132, dtype: int64
None       487797
1or2       143529
3or4        19182
4orMore      1610
Name: steward, dtype: int64
None       572254
Helpful     51864
Harmful     20252
Unsure       7748
Name: guards, dtype: int64
NoDamage    464934
Damage      187184
Name: sidewalk, dtype: int64
TreesCount Staff    282236
Volunteer           207772
NYC Parks Staff     162110
Name: user_type, dtype: int64
None                                                                426276
Stones                                                               95671
BranchLights                                                         29452
Stones,BranchLights                                                  17808
RootOther                                                            11418
                                                                     ...
Stones,WiresRope,TrunkLights,TrunkOther,BranchLights,BranchOther         1
TrunkOther,BranchLights,Sneakers,BranchOther                             1
MetalGrates,WiresRope,TrunkLights                                        1
WiresRope,TrunkOther,Sneakers                                            1
WiresRope,BranchLights,Sneakers                                          1
Name: problems, Length: 232, dtype: int64
No     512121
Yes    139997
Name: root_stone, dtype: int64
No     648582
Yes      3536
Name: root_grate, dtype: int64
No     621796
Yes     30322
Name: root_other, dtype: int64
No     638844
Yes     13274
Name: trnk_wire, dtype: int64
No     651087
Yes      1031
Name: trnk_light, dtype: int64
No     619545
Yes     32573
Name: trnk_other, dtype: int64
No     589753
Yes     62365
Name: brnch_ligh, dtype: int64
No     651707
Yes       411
Name: brnch_shoe, dtype: int64
No     627763
Yes     24355
Name: brnch_othe, dtype: int64
106 CROSS BAY BOULEVARD    210
2350 FOREST HILL ROAD      130
2 TELEPORT DRIVE           125
900 SOUTH AVENUE            88
2750 VETERANS ROAD WEST     78
                          ...
135-011 124 STREET           1
32-016 87 STREET             1
22-002 42 STREET             1
27 3 AVENUE                  1
262-008 82 AVENUE            1
Name: address, Length: 395393, dtype: int64
10312    21356
10314    16330
10306    12616
10309    12105
11234    10838
         ...
11697       24
10048       11
11451        9
11096        9
10115        7
Name: zipcode, Length: 191, dtype: int64
Brooklyn               169740
Staten Island          101417
Bronx                   80582
New York                61490
Jamaica                 24645
Flushing                22374
Ridgewood               10262
Fresh Meadows           10050
Astoria                  9542
Queens Village           9488
Whitestone               9016
Bayside                  8333
Springfield Gardens      7122
Little Neck              6994
Forest Hills             6742
Oakland Gardens          6731
Far Rockaway             6375
East Elmhurst            6154
Rosedale                 6078
Woodside                 5403
South Ozone Park         5200
Ozone Park               5173
Bellerose                4846
Middle Village           4666
Saint Albans             4448
Howard Beach             4381
Corona                   4124
Elmhurst                 4014
Glen Oaks                4005
Maspeth                  3797
Hollis                   3407
Long Island City         3335
Richmond Hill            3210
Rockaway Park            3176
Jackson Heights          3155
Cambria Heights          3061
College Point            2946
Rego Park                2909
Woodhaven                2714
South Richmond Hill      2625
Arverne                  1863
Kew Gardens              1666
Sunnyside                1615
Floral Park              1439
Central Park              932
New Hyde Park             840
Breezy Point               24
Inwood                      9
Name: zip_city, dtype: int64
503    51842
413    35180
407    29168
411    26907
412    24980
502    24886
501    24689
408    19556
318    18437
405    18431
305    15912
410    14353
315    12981
401    12395
312    11977
301    11542
414    11386
409    10878
210    10786
212    10522
403    10315
314    10120
310    10119
306     9913
406     9749
209     9597
211     9490
303     9165
311     9002
108     8888
107     8571
302     8474
402     8294
317     8060
307     7788
304     6817
112     6745
404     6372
204     6060
208     5789
110     5724
308     5529
309     5130
207     5093
316     5042
206     4894
106     4863
102     4833
109     4755
103     4705
202     4702
203     4613
111     4591
205     4520
201     4516
104     4419
313     3725
101     2297
105     2031
Name: cb_num, dtype: int64
4    237964
3    169733
5    101417
2     80582
1     62422
Name: borocode, dtype: int64
Queens           237964
Brooklyn         169733
Staten Island    101417
Bronx             80582
Manhattan         62422
Name: boroname, dtype: int64
51    49203
19    33011
50    32018
23    29213
31    21921
49    20196
27    18992
32    18255
24    18246
30    17543
13    16777
46    16159
28    14911
20    13441
39    13392
29    13269
43    12616
42    12572
33    12330
44    11240
45    11218
17    11138
48    11033
22    10976
37    10488
26    10254
34    10187
12    10177
35    10156
18     9452
11     9349
38     9075
47     8819
36     8750
4      8221
3      8201
41     7920
9      7870
6      7857
21     7604
15     7578
25     7519
8      6763
40     6587
7      6247
10     6122
16     5964
14     5856
1      5428
2      5316
5      4688
Name: cncldist, dtype: int64
62    44238
26    26624
64    22141
63    21137
25    20590
      ...
72     4795
39     4254
74     4051
76     3620
65     3526
Name: st_assem, Length: 65, dtype: int64
24    84119
11    64808
15    42101
14    36185
10    33171
34    29641
19    27793
22    26039
23    24097
16    22989
25    22683
17    21275
12    20783
21    19849
18    19638
13    17920
20    16186
26    15802
32    15093
36    13757
33    13552
29    13388
30    13279
27    13111
28    12657
31    12202
Name: st_senate, dtype: int64
SI01    12530
SI54    10267
QN46     9386
BK82     9188
SI32     8842
        ...
MN06      865
BX46      773
BK93      671
BK23      455
MN50      438
Name: nta, Length: 188, dtype: int64
Annadale-Huguenot-Prince's Bay-Eltingville    12530
Great Kills                                   10267
Bayside-Bayside Hills                          9386
East New York                                  9188
Rossville-Woodrow                              8842
                                              ...
Manhattanville                                  865
Parkchester                                     773
Starrett City                                   671
West Brighton                                   455
Stuyvesant Town-Cooper Village                  438
Name: nta_name, Length: 188, dtype: int64
5020801    3620
5017600    3143
5020804    2611
5020803    2608
5019800    2545
           ...
3025902       7
1011300       6
3028502       4
2031900       3
5001800       2
Name: boro_ct, Length: 2152, dtype: int64
New York    652118
Name: state, dtype: int64
40.660359    35
40.610977    27
40.615966    17
40.689461    17
40.778497    11
             ..
40.736478     1
40.908074     1
40.689808     1
40.745004     1
40.661284     1
Name: Latitude, Length: 645116, dtype: int64
-73.761035    35
-74.156861    28
-73.752750    17
-73.956801    17
-73.797647    11
              ..
-73.999045     1
-73.888075     1
-73.851763     1
-74.012868     1
-73.867146     1
Name: longitude, Length: 646032, dtype: int64
1.050550e+06    35
9.406974e+05    27
9.962435e+05    17
1.052818e+06    17
1.040292e+06    11
                ..
9.542835e+05     1
1.007566e+06     1
1.039450e+06     1
1.004402e+06     1
1.038997e+06     1
Name: x_sp, Length: 651028, dtype: int64
179953.550904    35
161910.811399    27
190562.439463    17
163692.339660    17
222968.987511    11
                 ..
180381.550376     1
232023.031082     1
154073.100696     1
141482.044186     1
167220.599008     1
Name: y_sp, Length: 651067, dtype: int64

In [22]:
print(df.dtypes)

created_at     object
tree_id         int64
block_id        int64
tree_dbh        int64
stump_diam      int64
curb_loc       object
status         object
health         object
spc_latin      object
spc_common     object
steward        object
guards         object
sidewalk       object
user_type      object
problems       object
root_stone     object
root_grate     object
root_other     object
trnk_wire      object
trnk_light     object
trnk_other     object
brnch_ligh     object
brnch_shoe     object
brnch_othe     object
address        object
zipcode         int64
zip_city       object
cb_num          int64
borocode        int64
boroname       object
cncldist        int64
st_assem        int64
st_senate       int64
nta            object
nta_name       object
boro_ct         int64
state          object
Latitude      float64
longitude     float64
x_sp          float64
y_sp          float64
dtype: object

In [29]:
# Is the date format correct?
df['created_at'] = df['created_at'].astype('datetime64[ns]')


# No blank spaces (ex: " I love python " => "I love python")
df['spc_latin'] = df['spc_latin'].str.strip()
df['spc_common'] = df['spc_common'].str.strip()

# Are there some columns where most of the data is missing ? => all same value
df.drop('status',axis=1)
df.drop('stump_diam',axis=1)

#Can values be consolidated? (e.g. Truck and truck refer to the same thing) => opposite in column problems
#No
# Are some values integers that should be float or vice-versa ? Change the dtype.
#No

,created_at,tree_id,block_id,tree_dbh,stump_diam,curb_loc,health,spc_latin,spc_common,steward,...,st_assem,st_senate,nta,nta_name,boro_ct,state,Latitude,longitude,x_sp,y_sp
the_geom,,,,,,,,,,,,,,,,,,,,,
POINT (-73.84421521958048 40.723091773924274),2015-08-27,180683,348711,3,0,OnCurb,Fair,Acer rubrum,red maple,None,...,28,16,QN17,Forest Hills,4073900,New York,40.723092,-73.844215,1.027431e+06,202756.768749
POINT (-73.81867945834878 40.79411066708779),2015-09-03,200540,315986,21,0,OnCurb,Fair,Quercus palustris,pin oak,None,...,27,11,QN49,Whitestone,4097300,New York,40.794111,-73.818679,1.034456e+06,228644.837379
POINT (-73.93660770459083 40.717580740099116),2015-09-05,204026,218365,3,0,OnCurb,Good,Gleditsia triacanthos var. inermis,honeylocust,1or2,...,50,18,BK90,East Williamsburg,3044900,New York,40.717581,-73.936608,1.001823e+06,200716.891267
POINT (-73.93445615919741 40.713537494833226),2015-09-05,204337,217969,10,0,OnCurb,Good,Gleditsia triacanthos var. inermis,honeylocust,None,...,53,18,BK90,East Williamsburg,3044900,New York,40.713537,-73.934456,1.002420e+06,199244.253136
POINT (-73.97597938483258 40.66677775537875),2015-08-30,189565,223043,21,0,OnCurb,Good,Tilia americana,American linden,None,...,44,21,BK37,Park Slope-Gowanus,3016500,New York,40.666778,-73.975979,9.909138e+05,182202.425999
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
POINT (-73.95494401022562 40.7132107823145),2015-08-18,155433,217978,25,0,OnCurb,Good,Quercus palustris,pin oak,None,...,53,18,BK73,North Side-South Side,3051900,New York,40.713211,-73.954944,9.967407e+05,199121.636255
POINT (-73.85665019989099 40.71519444267162),2015-08-29,183795,348185,7,0,OnCurb,Good,Cladrastis kentukea,Kentucky yellowwood,1or2,...,28,15,QN17,Forest Hills,4070700,New York,40.715194,-73.856650,1.023989e+06,199873.647547
POINT (-74.13651724205825 40.62076152739799),2015-08-22,166161,401670,12,0,OnCurb,Good,Acer rubrum,red maple,None,...,63,24,SI07,Westerleigh,5020100,New York,40.620762,-74.136517,9.463514e+05,165466.076270
POINT (-73.90311472453581 40.850828186655754),2015-08-29,184028,504204,9,0,OnCurb,Good,Acer rubrum,red maple,None,...,86,33,BX41,Mount Hope,2023502,New York,40.850828,-73.903115,1.011054e+06,249271.950653
POINT (-73.78752645502483 40.73216525220126),2015-09-03,200607,306527,23,0,OnCurb,Fair,Acer rubrum,red maple,None,...,25,11,QN41,Fresh Meadows-Utopia,4134100,New York,40.732165,-73.787526,1.043136e+06,206095.538318